CREATE DATABASE MEDCONTROL;
USE MEDCONTROL;

CREATE TABLE `USER`(
	`ID` INT PRIMARY KEY AUTO_INCREMENT,
    `NAME` VARCHAR(100) NOT NULL,
    `EMAIL` VARCHAR(100) UNIQUE,
    `PASSWORD_HASH` VARCHAR(255),
    `PHONE` VARCHAR(20),
    `DATE_OF_BIRTH` DATE,
    `CREATED_AT` TIMESTAMP,
    `UPDATED_AT` TIMESTAMP
);

CREATE TABLE `MEDICATION`(
	`ID` INT PRIMARY KEY AUTO_INCREMENT,
    `USER_ID` INT,
    `NAME` VARCHAR(100),
    `TYPE` ENUM('comum', 'manipulado') NOT NULL,
	`FREQUENCY` VARCHAR(50),
    `TIME` TIME,
    `START_DATE` DATE,
    `END_DATE` DATE,
    `NOTES` TEXT,
    `DOSAGE` FLOAT,
    `FORM` VARCHAR(50),
    `ADMINISTRATION_INSTRUCTIONS` TEXT,
    `IMAGE_PATH` VARCHAR(255),
    `COMMON_SIDE_EFFECTS` TEXT,
    `STOCK` INT,
    `CREATED_AT` TIMESTAMP,
    `UPDATED_AT` TIMESTAMP,
    `UNIT` VARCHAR(2),
    
    FOREIGN KEY (`USER_ID`) REFERENCES `USER`(ID)
);

CREATE TABLE `MEDICATION_COMPONENT`(
    `ID` INT AUTO_INCREMENT PRIMARY KEY,
    `MEDICATION_ID` INT NOT NULL,
    `NAME_COMPONENT` VARCHAR(100) NOT NULL,
    `DOSAGE` FLOAT NOT NULL,
    `UNIT` VARCHAR(2) NOT NULL,
    FOREIGN KEY (`MEDICATION_ID`) REFERENCES `MEDICATION`(ID) ON DELETE CASCADE
);

CREATE TABLE `DOSE`(
	`ID` INT PRIMARY KEY AUTO_INCREMENT,
    `MEDICATION_ID` INT,
    `SCHEDULED_TIME` DATETIME,
    `TAKEN_TIME` DATETIME,
    `STATUS` ENUM('scheduled', 'taken', 'missed'),
    `NOTES` TEXT,
    
    FOREIGN KEY (`MEDICATION_ID`) REFERENCES `MEDICATION`(ID)
);

CREATE TABLE `NOTIFICATION_SETTING`(
	`ID` INT PRIMARY KEY AUTO_INCREMENT,
    `USER_ID` INT,
    `MEDICATION_ID` INT,
    `PUSH_ENABLED` BOOLEAN,
    `REMINDER_TIME` TIME,
    
    FOREIGN KEY (`USER_ID`) REFERENCES `USER`(ID),
    FOREIGN KEY (`MEDICATION_ID`) REFERENCES `MEDICATION`(ID)
);

CREATE TABLE `MEDICAL_RECORD`(
	`ID` INT PRIMARY KEY AUTO_INCREMENT,
    `USER_ID` INT,
    `RECORD_TYPE` VARCHAR(50),
    `FILE_PATH` VARCHAR(255),
    `DATE` DATE,
    `NOTES` TEXT,
    
    FOREIGN KEY (`USER_ID`) REFERENCES `USER`(ID)
);

CREATE TABLE `SIDE_EFFECT`(
	`ID` INT PRIMARY KEY AUTO_INCREMENT,
    `MEDICATION_ID` INT,
    `USER_ID` INT,
    `DESCRIPTION` TEXT,
    `SEVERITY` ENUM('mild', 'moderate', 'severe'),
    `DATE` DATE,
    `NOTES` TEXT,
    
    FOREIGN KEY (`MEDICATION_ID`) REFERENCES `MEDICATION`(ID),
    FOREIGN KEY (`USER_ID`) REFERENCES `USER`(ID)
);